package com.example.mobp2.dto

data class AnimalInShelterResponse(
    val desertionNo: String?,
    val rfidCd: String?,
    val happenDt: String?,
    val happenPlace: String?,
    val kindFullNm: String?,
    val upKindCd: String?,
    val upKindNm: String?,
    val kindCd: String?,
    val kindNm: String?,
    val colorCd: String?,
    val age: String?,
    val weight: String?,
    val noticeNo: String?,
    val noticeSdt: String?,
    val noticeEdt: String?,
    val popfile1: String?,
    val popfile2: String?,
    val processState: String?,
    val sexCd: String?,
    val neuterYn: String?,
    val specialMark: String?,
    val careRegNo: String?,
    val careNm: String?,
    val careTel: String?,
    val careAddr: String?,
    val careOwnerNm: String?,
    val orgNm: String?,
    val etcBigo: String?,
    val updTm: String?,
)
