package com.example.mobp2.dto

data class ShelterResponse(
    val careNm: String?,
    val careRegNo: String?,
    val orgNm: String?,
    val divisionNm: String?,
    val saveTrgtAnimal: String?,
    val careAddr: String?,
    val jibunAddr: String?,
    val lat: Double?,
    val lng: Double?,
    val dsignationDate: String?,
    val weekOprStime: String?,
    val weekOprEtime: String?,
    val weekCellStime: String?,
    val weekCellEtime: String?,
    val weekendOprStime: String?,
    val weekendOprEtime: String?,
    val weekendCellStime: String?,
    val weekendCellEtime: String?,
    val closeDay: String?,
    val vetPersonCnt: Int?,
    val specsPersonCnt: Int?,
    val medicalCnt: Int?,
    val breedCnt: Int?,
    val quarabtineCnt: Int?,
    val feedCnt: Int?,
    val transCarCnt: Int?,
    val careTel: String?,
    val dataStdDt: String?,
)
